### ISSUE TITLE
Images in Product Features box

### ISSUE THREAD

**Issue by TOABridget** [westoforange/TOA-Website#142]
Any image inserted into a 'Product Features' box on any product pages does not appear.
Example: http://toaelectronics.com/products/wired-microphones/am-1-array-microphone
Scroll to the bottom and you will see 'AM1 GUI' with no image.
View this page in the backend and the image is there.

**Comment by TOABridget** [comment]
We're now getting customer complaints about wanting to see our products, but cannot because images on each product page in the scrolling box do not appear at all or do not appear correctly.

**Comment by ecommarato** [comment]
The images in the slider are completely separate from the images under Media but the slider shows images in a certain way.  

I'll use AM-1 http://toaelectronics.com/adm1n3907/mod_products_a.php?action=edit_product&prodid=251 as an example:

The product page will first show the image that has been uploaded as the product image at the top (the image uploader under Product Category).  However, if there are images uploaded in the product's Image Library (scroll to the bottom under "Related Products"), then it will show these in the slider instead. 

The photos added under "Media" are never shown because these are generally huge files that you probably don't want taking up bandwidth in the slider!

**Comment by TOABridget** [comment]
We only have images in 2 sizes at the moment, does this mean we need to resize every image on the entire site so that one is for the media library, one is for the slider, and one is for the page? Seems redundant as if 1 image for any spot should be sufficient and be resized automatically.
@ecommarato @bobtoa602 @rescobar2

**Comment by ecommarato** [comment]
The CMS doesn't automatically resize images when they are uploaded, but I can add this as part of a change request.  Sounds like it will save you a lot of work if it can automatically place the resized image in the slider for you!

**Comment by ecommarato** [comment]
Checking for update on this

**Comment by TOABridget** [comment]
This is really old, I think it was resolved.
