### ISSUE TITLE
http://toaelectronics.com/corporate page issues

### ISSUE THREAD

**Issue by rescobar2** [westoforange/TOA-Website#20]
Load: http://toaelectronics.com/corporate

All Issues for this page
Under Products only the TS-770 image is hyper linked
Trantec image is missing

Resources (at bottom left of the page)
    Corporate Brochure (not linked)
    Case Studies (not linked)

**Comment by bobtoa602** [comment]
THIS LINK IS POINTING TO THE WRONG PAGE ENTIRELY. SHOULD BE TOA CORPORATE INFORMATION, NOT CORPORATE APPLICATIONS.

**Comment by bobtoa602** [comment]
BTW-SAME ISSUE UNDER "CORPORATE/CONTACT US" DROP DOWN

**Comment by ecommarato** [comment]
I can't find some of these products to add their links.  Bridget, help!!

**Comment by TOABridget** [comment]
I can certainly help once it points the correct page, it currently does not.

**Comment by ecommarato** [comment]
I think I need help with this page! What is the correct title for this page and where should it be linked?

**Comment by TOABridget** [comment]
I don't see a 'Corporate' page at all, I just get a 404 error. Anything that points to 'corporate-applications' or 'about-corporate' needs to point to the 'about us' page. I think the confusion is that 'Corporate' under 'About Us' needs to be deleted until we can populate that properly. That should clear up that confusion. I think Bob got really lost when he was describing what he was describing since that page doesn't exist! A simple link change for now would be great, I'll fill in the rest when we get there. Does that make sense?

**Comment by ecommarato** [comment]
Removed Corporate link from About Us and Contact Us
