### ISSUE TITLE
'Our Products' titles

### ISSUE THREAD

**Issue by TOABridget** [westoforange/TOA-Website#83]
Can I change category titles in this box? @ecommarato or is that something you have to do?

**Comment by ecommarato** [comment]
You can change the product categories, which will change them in the Our Product box AND everywhere on the site.  To do this, go to Products in the CMS and navigate to the category you wish to edit.  Instead of clicking into the category, click the edit button on the far right of the category name.  You can then edit the category's name.

**Comment by TOABridget** [comment]
Excellent, thanks! We still need more space between the category names in the products list, or maybe a small faded line between. So far, one category now takes up 2 lines and it looks a little lost.

**Comment by ecommarato** [comment]
I added some space in between the categories.  See if that looks better.

**Comment by TOABridget** [comment]
I think that works. Should we want it a different way, we'll let you know.
